<?php require_once './../View/nav.phtml'; ?>

<div class="products">
    <?php if (empty($userProducts)) { ?>
    <h2>Cart is empty</h2>
    <?php } else {
    foreach ($userProducts as $userProduct):
    $product = $products[$userProduct->getProductId()]; ?>
        <div class="product">
            <img src="<?php echo $product->getImgUrl(); ?>">

            <h1><?php echo $product->getName(); ?></h1>

            <h2>Описание: <?php echo $product->getDescription(); ?></h2>

            <p>Стоимость: <?php echo $product->getPrice(); ?> ₽</p>

            <p>Количичество: <span class="quantity-display"><?php echo $userProduct->getQuantity(); ?></span> </p>

            <?php $totalPrice += $product->getPrice() * $userProduct->getQuantity(); ?>

            <div>
                <form class="quantity-form" data-action="plus" onsubmit="return false" method="post">

                    <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>">

                    <button class="quantity-btn" type="submit" value="inc">+</button>
                </form>
                <form class="quantity-form" data-action="minus" onsubmit="return false" action="/product-minus" method="post">

                    <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>">

                    <button class="quantity-btn" type="submit" value="dec">-</button>
                </form>
            </div>

        </div>
    <?php endforeach; } ?>
</div>

<div>
    <h1  class="total-Price">Сумма к оплате: <?php echo $totalPrice; ?></h1>
</div>

<div class="order-container">
    <form class="order-form" action="/order" method="post">

        <div class="order-form-field">
            <label for="phone"><b>Phone</b></label>
            <?php   if (isset($errors['user_phone'])): ?>
                <div class="labelError">
                    <label><?php echo $errors['user_phone']; ?></label>
                </div>
            <?php endif; ?>
            <input type="text" placeholder="Enter Phone" name="phone" id="phone" required>
        </div>

        <div class="order-form-field">
            <label for="address"><b>Address</b></label>
            <?php   if (isset($errors['user_address'])): ?>
                <div class="labelError">
                    <label><?php echo $errors['user_address']; ?></label>
                </div>
            <?php endif; ?>
            <input type="text" placeholder="Enter Address" name="address" id="address" required>
        </div>

        <button class="order-btn">Оформить заказ</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $("document").ready(function() {
        $('.quantity-form').submit(function() {
            var action = $(this).data('action');
            var quantityDisplay = $(this).closest('.product').find('.quantity-display');

            $.ajax({
                type: "POST",
                url: "/product-" + action,
                // dataType: 'html',
                data: $(this).serialize(),
                success: function() {
                    console.log('done');
                    updateQuantityDisplay(quantityDisplay, action);
                }
            })
        });

        function updateQuantityDisplay(displayElement, action) {
            // Получаем текущее значение количества из интерфейса
            var currentQuantity = parseInt(displayElement.text());
            if (currentQuantity > 0) {
                if (action === 'plus') {
                    currentQuantity++;
                } else if (action === 'minus') {
                    currentQuantity--;
                }
            }

            // Устанавливаем новое значение в интерфейсе
            displayElement.text(currentQuantity);

            if (currentQuantity < 1) {
                displayElement.closest('.product').remove();
            }
        }
    });

</script>

<style>

    a {
        &:hover{
            border-bottom: 3px red solid ;
        }
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin: 0;

    }

    .labelError {
        color: red;
    }

    .order-container {
        display: grid;
        place-items: center;
        height: 100%;
        max-height: 300px/* Высота 100% экрана, чтобы форма оставалась по центру */
    }

    .order-form-field {
        max-width: 300px;
        text-align: center;
    }

    * {box-sizing: border-box}

    /* Full-width input fields */
    input[type=text], input[type=password] {
        max-width: 200px;
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #8888;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    .order-btn {
        background-color: #04AA6D;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        max-width: 200px;
        width: 100%;
        opacity: 0.9;
    }

    .order-btn:hover {
        opacity:1;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    header {
        margin-top: 30px;
    }

    h1, h2, h3 {
        text-align: center;
        color: #333;
    }

    .product img {
        max-height: 300px;
        max-width: 300px;
    }

    .products {
        width: 820px;
        margin: 0 auto;
        display: inline-flex;
        flex-direction: row;
        flex-wrap: wrap;

    }


    .product {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        width: 300px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .product img {
        height: 100%;
        width: 100%;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    .product h2 {
        color: #666;
        font-size: 18px;
    }

    .product p {
        color: #999;
    }


    nav {
        background-color: #f2f2f2;
        padding: 10px;
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: space-between;
    }

    li {
        display: inline;
        margin-right: 10px;
    }

    a {
        text-decoration: none;
        color: #333;
        padding: 5px;
    }

    a:hover {
        text-decoration: none;
        background-color: #333;
        color: #fff;
    }

    .order-form {
        text-align: center;
    }
</style>
