<?php require_once './../View/nav.phtml'; ?>

<div class="products">
    <?php foreach ($products as $product): ?>
        <div class="product">
            <img src="<?php echo $product->getImgUrl(); ?>">

            <h1><?php echo $product->getName(); ?></h1>

            <h2><?php echo $product->getDescription(); ?></h2>

            <p><?php echo $product->getPrice(); ?> ₽</p>
            <div>
                <form class="quantity-form" data-action="plus" onsubmit="return false" method="post">

                    <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>">

                    <button class="quantity-btn" type="submit" value="inc">+</button>
                </form>
                <form class="quantity-form" data-action="minus" onsubmit="return false" action="/product-minus" method="post">

                    <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>">

                    <button class="quantity-btn" type="submit" value="dec">-</button>
                </form>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $("document").ready(function() {
        $('.quantity-form').submit(function() {
            var action = $(this).data('action');

            $.ajax({
                type: "POST",
                url: "/product-" + action,
                // dataType: 'html',
                data: $(this).serialize(),
                success: function() {
                    console.log('done');
                }
            })
        });
    });
</script>

<style>

    a {
        &:hover{
            border-bottom: 3px red solid ;
        }
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin: 0;

    }

    header {
        margin-top: 30px;
    }

    h1, h2, h3 {
        text-align: center;
        color: #333;
    }

    .product img {
        max-height: 300px;
        max-width: 300px;
    }

    .products {
        width: 820px;
        margin: 0 auto;
        display: inline-flex;
        flex-direction: row;
        flex-wrap: wrap;

    }


    .product {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        width: 300px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .product img {
        height: 100%;
        width: 100%;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    .product h2 {
        color: #666;
        font-size: 18px;
    }

    .product p {
        color: #999;
    }


    nav {
        background-color: #f2f2f2;
        padding: 10px;
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: space-between;
    }

    li {
        display: inline;
        margin-right: 10px;
    }

    a {
        text-decoration: none;
        color: #333;
        padding: 5px;
    }

    a:hover {
        text-decoration: none;
        background-color: #333;
        color: #fff;
    }
</style>
